### ISSUE TITLE
Metal Slader Glory - Translated version bug

### ISSUE THREAD

**Issue by icelaglace** [MiSTer-devel/NES_MiSTer#269] opened 2021-09-13 07:57 UTC
Game name : Metal Slader Glory (Japan)
Using translated patch : https://www.romhacking.net/translations/3755
Original ROM MD5 : 7DD2B652E08E7A5214F8FF7FEFBA8A06

~~Issue 1 :~~
~~- Only at the beginning of the game, there's an odd line in the middle.~~
~~How it looks on MiSTer : https://i.imgur.com/rgEVGQF.mp4~~
~~Emulation reference : https://youtu.be/K8hNT5C8rqc?t=1173~~
    EDIT : Seems to happen on OG hardware too : https://youtu.be/FreP-r5XSmc?t=520

Issue 2 :
- All over the game, during special cutscenes, the portrait images are glitching in the middle on the screen in various occasions.
How it looks on MiSTer : https://i.imgur.com/kpAy8n2.mp4
Emulation reference : https://youtu.be/K8hNT5C8rqc?t=16100
If anyone can provide some real hardware footage, please do! I cannot find any and do not own a modern flashcart.

NES core display settings have Hide Overscan and Both Mask Edges on.

To go to the specific parts without playing the game for Issue #2 
- Run the ROM
- Press "Continue"
- Type "LET'S DEBUG!"
- Press : "STAGE JUMP"
- Press : "6. STAGE 7"
- Press : "ENDING"

**Comment by paulb-nl** [comment] 2021-09-13 15:21
Issue 2 seems to be caused by the scanline IRQ counter not being implemented properly like described on the Nesdev wiki.

There are two IRQs on that screen. The first is at line 25. Rendering is disabled and the second IRQ is set at line 124. Rendering is re-enabled at Hblank of line 34. This means the next IRQ should happen at 35+124 = line 159 but instead it looks like the IRQ happens at line 124 because we are simply comparing the PPU scanline counter.

**Comment by paulb-nl** [comment] 2022-04-04 08:20
Fixed in release 20220326 by d2fc19c375c8c53ab9aebc30fdaab463e3590445

**Closed** 2022-04-04 12:10 UTC
