### ISSUE TITLE
Pal Music Speed on some Games to slow

### ISSUE THREAD

**Issue by diettelo** [MiSTer-devel/NES_MiSTer#256] opened 2021-05-23 17:41 UTC
Some Games like Metal Gear, Mega Man, Mega Man 2 are to slow on Pal.
I have Pal roms and also tried Ntsc Mode its to fast. I cheked with a Video and also with my Original Nes. Its like the Speed is 90-95%. I think its only the Game Music and not Gameplay

**Comment by Kitrinx** [comment] 2021-05-23 22:06
give me recordings of both the real PAL NES with a PAL game and then a recording of the same PAL ROM from the core.

**Comment by diettelo** [comment] 2021-05-24 07:33
I will try to record. but for now i must find a way to record the real nes hardware, with cheap invest for recording hardware.

**Comment by Yamato-san** [comment] 2021-05-24 10:00
I own an original PAL NES and a copy of Mega Man 2 PAL-Version. I've compared it side-by-side with a Mega Man 2 PAL-ROM on the NES MiSTer core in PAL mode. Music speed really is the same. Even after a couple of minutes the music stills plays in sync.

@diettelo: Did you load up the Mega Man 2 PAL-Rom after you have set the region to PAL?

**Comment by diettelo** [comment] 2021-05-24 10:06
Yes. i load nes core and in my case its allready set to pal. for me mega man 2 tutle screen music is a little bit slow on pal with pal rom. also i was watching this on metal gear

**Comment by Yamato-san** [comment] 2021-05-24 10:31
I made a **quick and dirty** comparison with my mobile phone.
Original.m4a is for the real PAL NES console with original PAL Mega Man 2 cartridge inserted.
MiSTer.m4a is for - you guessed it - the PAL Mega Man 2 ROM on the MiSTer core in PAL mode.

I honestly can not hear any difference in music speed.

[http://nescenter.de/Original.m4a](Original PAL)
[http://nescenter.de/MiSTer.m4a](MiSTer PAL)

I'm outputting video and audio signals with the I/O board to a CRT television.

**Comment by SegaSnatcher** [comment] 2021-05-24 10:44
> I made a **quick and dirty** comparison with my mobile phone.
> Original.m4a is for the real PAL NES console with original PAL Mega Man 2 cartridge inserted.
> MiSTer.m4a is for - you guessed it - the PAL Mega Man 2 ROM on the MiSTer core in PAL mode.
> 
> I honestly can not hear any difference in music speed.
> [Original PAL](http://nescenter.de/Original.m4a)
> [MiSTer PAL](http://nescenter.de/MiSTer.m4a)
> 
> I'm outputting video and audio signals with the I/O board to a CRT television.

Interesting comparison.  Makes me wonder why the real NES sounds so much brighter/crisp where as MiSTer sounds kinda flatter in the EQ.

**Comment by Yamato-san** [comment] 2021-05-24 10:49
#Interesting comparison. Makes me wonder why the real NES sounds so much brighter/crisp where as MiSTer sounds kinda flatter in the EQ.

Well, as I said it was a QUICK AND DIRTY comparison with my my mobile phone held next to a CRT speaker.
This was made just for a comparison regarding music speed.
In real it sounds the same quality wise!

**Comment by SegaSnatcher** [comment] 2021-05-24 10:51
> > Interesting comparison. Makes me wonder why the real NES sounds so much brighter/crisp where as MiSTer sounds kinda flatter in the EQ.
> 
> Well, as I said it was a QUICK AND DIRTY comparison with my my mobile phone held next to a CRT speaker.
> This was made just for a comparison regarding music speed.
> In real it sounds the same quality wise!

Yeah, I just noticed the cell phone comment lol, but as far as speed is concerned I do not hear any difference.

**Comment by Kitrinx** [comment] 2021-05-24 11:42
The two samples provided appear to be identical in speed. In this comparison if the beginnings are aligned, the two stay in sync for their entire durations. The differences in waveform are from the quick and dirty phone recordings, but you can clearly see the major audio shifts.

![image](https://user-images.githubusercontent.com/15653832/119342670-4370cd80-bc4a-11eb-8b16-bb437684d50e.png)

**Comment by Kitrinx** [comment] 2021-05-25 16:36
Please either post some samples of the error or close this bug report. It appears to be otherwise unable to be reproduced.

**Comment by Kitrinx** [comment] 2021-07-07 11:00
Closing this due to lack of reproducibility or any further feedback from the original poster.

**Closed by Kitrinx** 2021-07-07 11:00 UTC
